const $=id=>document.getElementById(id), money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number.isFinite(+n)?+n:0), num=id=>parseFloat($(id).value)||0;
const fieldIds=['productId','buyCost','salesTax','sellPrice','referralPct','fulfillmentFee','inboundShipping','prepCost','miscFees','monthlyUnits','discount','prepCenterFee','returnAllowance','minProfit','minRoi','minMargin','maxSellers'];
let product=null,current={},deferredPrompt,stream,scanTimer,chartRange=90;
function escapeHtml(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function getConnection(){try{return JSON.parse(localStorage.getItem('flipgauge-v3-connection'))||{mode:'demo',baseUrl:'',token:''}}catch{return{mode:'demo',baseUrl:'',token:''}}}
function saveSettings(){const d={};fieldIds.forEach(id=>d[id]=$(id).value);localStorage.setItem('flipgauge-v3-settings',JSON.stringify(d));}
function loadSettings(){try{const d=JSON.parse(localStorage.getItem('flipgauge-v3-settings'));if(d)fieldIds.forEach(id=>{if(d[id]!=null)$(id).value=d[id]})}catch{}}
function setMessage(text,type='muted'){$('lookupMessage').className='message '+type;$('lookupMessage').innerHTML=text;}
function updateConnectionBadge(){const c=getConnection(),api=c.mode==='api';$('connectionBtn').textContent=api?'API mode':'Demo data';$('connectionBtn').className='status-pill '+(api?'live':'demo');}
async function lookupProduct(){const id=$('productId').value.trim().toUpperCase();if(!id)return setMessage('Enter or scan a UPC, EAN, or ASIN.','error');setMessage('Looking up product…','loading');$('lookupBtn').disabled=true;try{const c=getConnection();let data;if(c.mode==='demo'){await new Promise(r=>setTimeout(r,350));data=window.FLIPGAUGE_DEMO_CATALOG[id];if(!data)throw new Error('Not found in demo catalog. Try 012345678905, 036000291452, B0DEMO1234, or B0RISK9999.');}else{if(!c.baseUrl)throw new Error('Set an API base URL in Settings.');const res=await fetch(c.baseUrl.replace(/\/$/,'')+'/product-lookup?id='+encodeURIComponent(id),{headers:c.token?{Authorization:'Bearer '+c.token}:{}});if(!res.ok)throw new Error('API returned '+res.status);data=await res.json();}applyProduct(data);checkAlerts();setMessage('Product data loaded. Review the numbers before buying.','success');}catch(e){setMessage(escapeHtml(e.message||'Lookup failed.'),'error');}finally{$('lookupBtn').disabled=false}}
function applyProduct(p){product=p;$('productPanel').classList.remove('hidden');$('productImage').src=p.image||'icon.svg';$('productName').textContent=p.title||'Unnamed product';$('productCategory').textContent=p.category||'Uncategorized';$('productMeta').textContent=[p.asin&&'ASIN '+p.asin,p.upc&&'UPC '+p.upc,p.sizeTier,p.weight].filter(Boolean).join(' • ');$('buyBox').textContent=money(p.buyBox);$('lowestFba').textContent=money(p.lowestFba);$('salesRank').textContent=p.salesRank?Number(p.salesRank).toLocaleString():'—';$('salesEstimate').textContent=p.salesEstimate??'—';$('fbaSellers').textContent=p.fbaSellers??'—';$('amazonOnListing').textContent=p.amazonOnListing?'Yes':'No';setChip('eligibilityChip',p.eligible?'Eligible':(p.restrictedReason||'Restricted'),p.eligible?'good':'bad');setChip('amazonChip',p.amazonOnListing?'Amazon selling':'No Amazon offer',p.amazonOnListing?'warn':'good');setChip('hazmatChip',p.hazmat?'Hazmat review':'No hazmat flag',p.hazmat?'bad':'good');if(Number.isFinite(+p.buyBox))$('sellPrice').value=(+p.buyBox).toFixed(2);if(Number.isFinite(+p.referralPct))$('referralPct').value=(+p.referralPct).toFixed(2);if(Number.isFinite(+p.fulfillmentFee))$('fulfillmentFee').value=(+p.fulfillmentFee).toFixed(2);renderMarket();renderVariations();calculate();}
function setChip(id,text,kind){$(id).textContent=text;$(id).className='chip '+kind;}
function calculate(){const buyCost=Math.max(0,num('buyCost')-num('discount')),tax=buyCost*num('salesTax')/100,sellPrice=num('sellPrice'),referral=sellPrice*num('referralPct')/100,fulfillment=num('fulfillmentFee'),shipping=num('inboundShipping'),prep=num('prepCost')+num('prepCenterFee'),misc=num('miscFees'),returnCost=sellPrice*num('returnAllowance')/100,acquisition=buyCost+tax+shipping+prep,fees=referral+fulfillment+misc,profit=sellPrice-acquisition-fees,adjusted=profit-returnCost,roi=acquisition?adjusted/acquisition*100:0,margin=sellPrice?adjusted/sellPrice*100:0,rate=num('referralPct')/100,breakEven=(acquisition+fulfillment+misc)/(1-rate||1),monthly=adjusted*num('monthlyUnits'),targetProfit=num('minProfit'),maxBuy=Math.max(0,(sellPrice-referral-fulfillment-misc-shipping-prep-returnCost-targetProfit)/(1+num('salesTax')/100));
const sellers=product?.fbaSellers??0,checks=[{label:'Profit',pass:adjusted>=num('minProfit')},{label:'ROI',pass:roi>=num('minRoi')},{label:'Margin',pass:margin>=num('minMargin')},{label:'Seller count',pass:!product||sellers<=num('maxSellers')},{label:'Eligible',pass:!product||product.eligible!==false},{label:'No hazmat flag',pass:!product||!product.hazmat},{label:'Amazon absent',pass:!product||!product.amazonOnListing}];
let score=0;score+=Math.min(25,Math.max(0,adjusted/Math.max(1,num('minProfit'))*20));score+=Math.min(20,Math.max(0,roi/Math.max(1,num('minRoi'))*16));score+=Math.min(15,Math.max(0,margin/Math.max(1,num('minMargin'))*12));score+=checks[3].pass?10:0;score+=checks[4].pass?15:0;score+=checks[5].pass?5:0;score+=checks[6].pass?10:0;score=Math.round(Math.min(100,score));let decision=score>=75&&checks[4].pass&&checks[5].pass?'BUY':score>=50&&checks[4].pass?'MAYBE':'PASS';
current={date:new Date().toISOString(),id:$('productId').value.trim(),asin:product?.asin||'',name:product?.title||'',buyCost,sellPrice,profit:adjusted,roi,margin,score,decision,salesRank:product?.salesRank??'',salesEstimate:product?.salesEstimate??'',fbaSellers:product?.fbaSellers??'',eligible:product?.eligible??'',amazonOnListing:product?.amazonOnListing??''};
$('profit').textContent=money(profit);$('riskAdjustedProfit').textContent=money(adjusted);$('roi').textContent=roi.toFixed(1)+'%';$('margin').textContent=margin.toFixed(1)+'%';$('breakEven').textContent=money(breakEven);$('amazonFees').textContent=money(fees);$('monthlyProfit').textContent=money(monthly);$('maxBuyCost').textContent=money(maxBuy);$('decision').textContent=decision;$('scoreText').textContent=score+'/100';$('scoreOrb').className='score-orb '+decision.toLowerCase();$('feeBreakdown').innerHTML=`<span>Tax <b>${money(tax)}</b></span><span>Referral <b>${money(referral)}</b></span><span>FBA <b>${money(fulfillment)}</b></span><span>Inbound <b>${money(shipping)}</b></span><span>Prep <b>${money(prep)}</b></span><span>Misc <b>${money(misc)}</b></span><span>Return allowance <b>${money(returnCost)}</b></span>`;$('ruleChecks').innerHTML=checks.map(c=>`<span class="rule ${c.pass?'pass':'fail'}">${c.pass?'✓':'✕'} ${escapeHtml(c.label)}</span>`).join('');saveSettings();}
function getHistory(){try{return JSON.parse(localStorage.getItem('flipgauge-v3-history'))||[]}catch{return[]}}
function setHistory(v){localStorage.setItem('flipgauge-v3-history',JSON.stringify(v));renderHistory();}
function renderHistory(){const h=getHistory();$('historyBody').innerHTML=h.length?h.map((r,i)=>`<tr><td><b>${escapeHtml(r.name||r.id||'Unnamed')}</b><br><small>${escapeHtml(r.asin||r.id||'')}</small></td><td>${money(r.buyCost)}</td><td>${money(r.sellPrice)}</td><td>${money(r.profit)}</td><td>${Number(r.roi).toFixed(1)}%</td><td>${r.score}</td><td><span class="badge ${r.decision.toLowerCase()}">${r.decision}</span></td><td><button class="ghost small" onclick="deleteRow(${i})">Delete</button></td></tr>`).join(''):'<tr><td colspan="8">No saved scans yet.</td></tr>';}
window.deleteRow=i=>{const h=getHistory();h.splice(i,1);setHistory(h)};
$('lookupBtn').onclick=lookupProduct;$('productId').addEventListener('keydown',e=>{if(e.key==='Enter')lookupProduct()});$('useBuyBoxBtn').onclick=()=>{if(product?.buyBox){$('sellPrice').value=product.buyBox;calculate()}};
$('saveBtn').onclick=()=>{calculate();const h=getHistory();h.unshift(current);setHistory(h.slice(0,500));$('saveBtn').textContent='Saved ✓';setTimeout(()=>$('saveBtn').textContent='Save scan',1000)};$('clearBtn').onclick=()=>{if(confirm('Clear all saved scans?'))setHistory([])};$('resetRulesBtn').onclick=()=>{Object.assign($('minProfit'),{value:5});$('minRoi').value=30;$('minMargin').value=15;$('maxSellers').value=20;calculate()};
$('exportBtn').onclick=()=>{const h=getHistory();if(!h.length)return alert('No saved scans to export.');const cols=['date','id','asin','name','buyCost','sellPrice','profit','roi','margin','score','decision','salesRank','salesEstimate','fbaSellers','eligible','amazonOnListing'],csv=[cols.join(','),...h.map(r=>cols.map(c=>'"'+String(r[c]??'').replaceAll('"','""')+'"').join(','))].join('\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='flipgauge-v3-scans.csv';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)};
fieldIds.forEach(id=>$(id).addEventListener('input',calculate));
async function startScan(){if(!navigator.mediaDevices?.getUserMedia)return alert('Camera scanning is not supported. Enter the code manually.');try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}}});$('video').srcObject=stream;await $('video').play();$('scannerWrap').classList.remove('hidden');if('BarcodeDetector'in window){const d=new BarcodeDetector({formats:['ean_13','ean_8','upc_a','upc_e','code_128']});scanTimer=setInterval(async()=>{try{const codes=await d.detect($('video'));if(codes.length){$('productId').value=codes[0].rawValue;stopScan();navigator.vibrate?.(120);lookupProduct()}}catch{}},450)}else alert('Automatic barcode reading is unavailable in this browser.');}catch{alert('Could not access the camera. Check browser permissions.')}}
function stopScan(){clearInterval(scanTimer);stream?.getTracks().forEach(t=>t.stop());$('scannerWrap').classList.add('hidden')}$('scanBtn').onclick=startScan;$('stopScanBtn').onclick=stopScan;
function openSettings(){const c=getConnection();$('dataMode').value=c.mode;$('apiBaseUrl').value=c.baseUrl||'';$('apiToken').value=c.token||'';$('settingsModal').classList.remove('hidden')}$('settingsBtn').onclick=openSettings;$('connectionBtn').onclick=openSettings;$('closeSettingsBtn').onclick=()=>$('settingsModal').classList.add('hidden');$('settingsModal').onclick=e=>{if(e.target===$('settingsModal'))$('settingsModal').classList.add('hidden')};$('saveConnectionBtn').onclick=()=>{localStorage.setItem('flipgauge-v3-connection',JSON.stringify({mode:$('dataMode').value,baseUrl:$('apiBaseUrl').value.trim(),token:$('apiToken').value.trim()}));updateConnectionBadge();$('settingsModal').classList.add('hidden');setMessage($('dataMode').value==='api'?'API mode enabled.':'Demo catalog enabled.','success')};

function renderMarket(){if(!product?.priceHistory?.length){$('marketPanel').classList.add('hidden');return}$('marketPanel').classList.remove('hidden');const rows=product.priceHistory.slice(-chartRange),prices=rows.map(x=>+x.buyBox).filter(Number.isFinite),avg=prices.reduce((a,b)=>a+b,0)/prices.length,low=Math.min(...prices),high=Math.max(...prices),spread=avg?(high-low)/avg*100:0;$('avg90').textContent=money(avg);$('low90').textContent=money(low);$('high90').textContent=money(high);$('priceStability').textContent=spread<8?'Stable':spread<18?'Moderate':'Volatile';$('rankDrops').textContent=product.rankDrops??'—';$('sellerShare').textContent=product.fbaSellers?Math.max(1,Math.round((product.salesEstimate||0)/product.fbaSellers))+' units/mo':'—';drawChart(rows)}
function drawChart(rows){const c=$('priceChart'),ctx=c.getContext('2d'),dpr=window.devicePixelRatio||1,w=c.clientWidth||700,h=230;c.width=w*dpr;c.height=h*dpr;ctx.scale(dpr,dpr);ctx.clearRect(0,0,w,h);const pad=34,vals=rows.flatMap(r=>[+r.buyBox,+r.lowestFba]).filter(Number.isFinite),min=Math.min(...vals)*.97,max=Math.max(...vals)*1.03,x=i=>pad+i*(w-pad*1.4)/Math.max(1,rows.length-1),y=v=>h-pad-(v-min)/(max-min||1)*(h-pad*1.5);ctx.strokeStyle='#33415f';ctx.lineWidth=1;for(let i=0;i<4;i++){const yy=pad+i*(h-pad*1.5)/3;ctx.beginPath();ctx.moveTo(pad,yy);ctx.lineTo(w-pad/2,yy);ctx.stroke()}[['buyBox','#6ee7b7'],['lowestFba','#60a5fa']].forEach(([key,color])=>{ctx.strokeStyle=color;ctx.lineWidth=2;ctx.beginPath();rows.forEach((r,i)=>{const xx=x(i),yy=y(+r[key]);i?ctx.lineTo(xx,yy):ctx.moveTo(xx,yy)});ctx.stroke()});ctx.fillStyle='#a9b3c9';ctx.font='11px system-ui';ctx.fillText(money(max),2,pad);ctx.fillText(money(min),2,h-pad)}
function renderVariations(){const list=product?.variations||[];if(!list.length){$('variationsPanel').classList.add('hidden');return}$('variationsPanel').classList.remove('hidden');const scored=list.map(v=>({...v,opp:Math.round(Math.min(100,(v.sales/(v.sellers||1))*2+(v.price||0)))})).sort((a,b)=>b.opp-a.opp);$('variationSummary').textContent=`${list.length} variations • Best opportunity: ${scored[0].name}`;$('variationBody').innerHTML=scored.map(v=>{const level=v.opp>=75?'high':v.opp>=45?'medium':'low';return `<tr><td><b>${escapeHtml(v.name)}</b><br><small>${escapeHtml(v.asin)}</small></td><td>${money(v.price)}</td><td>${Number(v.rank).toLocaleString()}</td><td>${v.sales}</td><td>${v.sellers}</td><td><span class="opportunity ${level}">${v.opp}/100</span></td><td><button class="ghost small" onclick="useVariation('${escapeHtml(v.asin)}')">Analyze</button></td></tr>`}).join('')}
window.useVariation=asin=>{const v=product?.variations?.find(x=>x.asin===asin);if(!v)return;$('sellPrice').value=v.price;product={...product,asin:v.asin,buyBox:v.price,salesRank:v.rank,salesEstimate:v.sales,fbaSellers:v.sellers,title:product.title+' — '+v.name};applyProduct(product)};
function getAlerts(){try{return JSON.parse(localStorage.getItem('flipgauge-v3-alerts'))||[]}catch{return[]}}function setAlerts(a){localStorage.setItem('flipgauge-v3-alerts',JSON.stringify(a));renderAlerts()}
function renderAlerts(){const a=getAlerts();$('alertsList').innerHTML=a.length?a.map((x,i)=>`<div class="alert-row ${x.triggered?'triggered':''}"><div><b>${escapeHtml(x.name||x.id)}</b> ${x.triggered?'✓ Triggered':''}<br><small>Price ≥ ${money(x.price)} • Profit ≥ ${money(x.profit)} • Sellers ≤ ${x.sellers}${x.note?' • '+escapeHtml(x.note):''}</small></div><button class="ghost small" onclick="deleteAlert(${i})">Delete</button></div>`).join(''):'<div class="message muted">No alerts yet.</div>'}window.deleteAlert=i=>{const a=getAlerts();a.splice(i,1);setAlerts(a)};
function checkAlerts(){if(!product)return;const a=getAlerts();let changed=false;a.forEach(x=>{if((x.asin===product.asin||x.id===$('productId').value.trim())&&product.buyBox>=x.price&&current.profit>=x.profit&&product.fbaSellers<=x.sellers){if(!x.triggered)changed=true;x.triggered=true;x.triggeredAt=new Date().toISOString()}});if(changed)navigator.vibrate?.([100,60,100]);setAlerts(a)}
$('createAlertBtn').onclick=()=>{if(!product)return alert('Look up a product first.');calculate();const a=getAlerts();a.unshift({asin:product.asin,id:$('productId').value.trim(),name:product.title,price:num('alertPrice'),profit:num('alertProfit'),sellers:num('alertSellers'),note:$('alertNote').value.trim(),triggered:false,created:new Date().toISOString()});setAlerts(a.slice(0,100));checkAlerts()};$('range30Btn').onclick=()=>{chartRange=30;$('range30Btn').className='primary small';$('range90Btn').className='ghost small';renderMarket()};$('range90Btn').onclick=()=>{chartRange=90;$('range90Btn').className='primary small';$('range30Btn').className='ghost small';renderMarket()};window.addEventListener('resize',()=>product&&renderMarket());

window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('installBtn').classList.remove('hidden')});$('installBtn').onclick=async()=>{if(deferredPrompt){deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;$('installBtn').classList.add('hidden')}};if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');loadSettings();updateConnectionBadge();calculate();renderHistory();renderAlerts();
